
url: "https://subindemo.github.io/"  
baseurl: "" 

title      : EMOLAB
email      : stm01@naver.com     #contact mail 
description: "전북대학교 심리학과 김종완 교수의 정서신경과학 랩" 
author     : Subin Seo 
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

locale: "ko-KR" # "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code

collections:
  portfolio:

markdown: kramdown

remote_theme : jekyll-agency